# --- KONFIGURACIJA KOJA RADI SVUGDJE ---

# Ako na računaru/Renderu postoji varijabla, koristi je. Ako ne postoji, koristi lokalne podatke.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/kupi_prodaj_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1601}
spring.datasource.driver-class-name=org.postgresql.Driver

# Port (lokalno 8080, na Renderu šta on dodijeli)
server.port=${PORT:8080}

# Hibernate automatsko kreiranje tabela
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Konfiguracija
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Ogranicenja velicina slika
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Za dublje gledanje errora
logging.level.org.springframework.security=DEBUG
logging.level.com.faruk.backend=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

imgbb.api.key=b0628db2e7d0d217493e81e0c15ba677

server.error.include-message=always
